# Generated by Django 2.0.9 on 2018-10-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181008_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpagetag',
            old_name='content_objects',
            new_name='content_object',
        ),
    ]
