# Generated by Django 2.0.9 on 2018-10-10 11:44

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postpage_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SvgImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[blog.models.validate_svg])),
            ],
            options={
                'verbose_name': 'SvgImage',
                'verbose_name_plural': 'Svg Images',
            },
        ),
    ]
